-- Atomic knowledge extracted from the user's completed Notion niche pages.
-- Each priority-A page contributes two diagnostic questions, two objection
-- responses, and one mandatory ethical rule. Cosmetics already has a dedicated
-- pilot seed in 0002 and is intentionally not duplicated here.

WITH seed (id, item_type, speaker, category, title, prompt_text, short_text, full_text, clarification_text, next_action_text, channel, tone, required_level, risk_level, source_kind, source_url, source_reference, status, version, normalized_key) AS (
  VALUES
  ('ki-a-clothing-q1', 'question_to_client', 'creator', 'business', 'Что сейчас происходит в бренде: запуск, новая коллекция, обновление страницы или регулярная работа', 'Что сейчас происходит в бренде: запуск, новая коллекция, обновление страницы или регулярная работа?', NULL, NULL, NULL, NULL, 'any', 'business', 'required', 'normal', 'notion', 'https://app.notion.com/p/3aba54abb3e281d18091f4bfa67ef8e3?pvs=204', 'Бренды одежды и текстиля', 'approved', 1, 'priority-a-clothing-question-1'),
  ('ki-a-clothing-q2', 'question_to_client', 'creator', 'context', 'Почему решили заняться контентом именно сейчас', 'Почему решили заняться контентом именно сейчас?', NULL, NULL, NULL, NULL, 'any', 'business', 'recommended', 'normal', 'notion', 'https://app.notion.com/p/3aba54abb3e281d18091f4bfa67ef8e3?pvs=204', 'Бренды одежды и текстиля', 'approved', 1, 'priority-a-clothing-question-2'),
  ('ki-a-clothing-ob1', 'objection_response', 'creator', 'objections', 'Ответ: «Нейросеть исказит нашу одежду»', 'Нейросеть исказит нашу одежду', 'Ответная тактика: - признать риск; - объяснить, что точность товара является обязательным условием; - заранее определить неизменяемые детали; - использовать контрольные исходники; - согласовать тестовый кадр; - не использовать результат, если модель, ткань, цвет, крой или декор переданы неверно.', 'Ответная тактика: - признать риск; - объяснить, что точность товара является обязательным условием; - заранее определить неизменяемые детали; - использовать контрольные исходники; - согласовать тестовый кадр; - не использовать результат, если модель, ткань, цвет, крой или декор переданы неверно.', NULL, 'Уточнить факты и согласовать безопасный следующий шаг.', 'any', 'firm', 'recommended', 'elevated', 'notion', 'https://app.notion.com/p/3aba54abb3e281d18091f4bfa67ef8e3?pvs=204', 'Бренды одежды и текстиля', 'approved', 1, 'priority-a-clothing-objection-1'),
  ('ki-a-clothing-ob2', 'objection_response', 'creator', 'objections', 'Ответ: «Покупатель поймёт, что это нейросеть»', 'Покупатель поймёт, что это нейросеть', 'Сместить разговор с сокрытия технологии на качество и честность подачи. Необходимо объяснить: задача — не обмануть покупателя, а создать выразительную рекламную среду вокруг реального продукта. Сам товар и его ключевые характеристики должны соответствовать действительности.', 'Сместить разговор с сокрытия технологии на качество и честность подачи. Необходимо объяснить: задача — не обмануть покупателя, а создать выразительную рекламную среду вокруг реального продукта. Сам товар и его ключевые характеристики должны соответствовать действительности.', NULL, 'Зафиксировать границы решения до начала производства.', 'any', 'firm', 'recommended', 'elevated', 'notion', 'https://app.notion.com/p/3aba54abb3e281d18091f4bfa67ef8e3?pvs=204', 'Бренды одежды и текстиля', 'approved', 1, 'priority-a-clothing-objection-2'),
  ('ki-a-clothing-eth1', 'ethical_rule', 'system', 'ethics', 'Обязательная проверка: Бренды одежды и текстиля', NULL, 'Скромная и уважительная подача. Отсутствие сексуализации. Отсутствие акцента на теле как инструменте привлечения внимания.', 'Скромная и уважительная подача. Отсутствие сексуализации. Отсутствие акцента на теле как инструменте привлечения внимания.', NULL, 'Скромная и уважительная подача. Отсутствие сексуализации. Отсутствие акцента на теле как инструменте привлечения внимания.', 'any', 'firm', 'required', 'high', 'notion', 'https://app.notion.com/p/3aba54abb3e281d18091f4bfa67ef8e3?pvs=204', 'Бренды одежды и текстиля', 'approved', 1, 'priority-a-clothing-ethics-1'),
  ('ki-a-jewelry-q1', 'question_to_client', 'creator', 'business', 'Что побудило клиента искать новый контент именно сейчас', 'Что побудило клиента искать новый контент именно сейчас?', NULL, NULL, NULL, NULL, 'any', 'business', 'required', 'normal', 'notion', 'https://app.notion.com/p/3aba54abb3e281abbea5fe4f6a2df4a3?pvs=204', 'Украшения и женские аксессуары', 'approved', 1, 'priority-a-jewelry-question-1'),
  ('ki-a-jewelry-q2', 'question_to_client', 'creator', 'context', 'Есть ли конкретный запуск, сезон или проблема', 'Есть ли конкретный запуск, сезон или проблема?', NULL, NULL, NULL, NULL, 'any', 'business', 'recommended', 'normal', 'notion', 'https://app.notion.com/p/3aba54abb3e281abbea5fe4f6a2df4a3?pvs=204', 'Украшения и женские аксессуары', 'approved', 1, 'priority-a-jewelry-question-2'),
  ('ki-a-jewelry-ob1', 'objection_response', 'creator', 'objections', 'Ответ: «Нейросеть изменит мой товар»', 'Нейросеть изменит мой товар', 'Ответная тактика: - признать обоснованность страха; - объяснить, что форма, материал, цвет, фурнитура, камни и пропорции фиксируются как критически важные признаки; - предложить контрольные сравнения с исходником; - определить допустимый и недопустимый уровень изменений до начала работы; - для точных карточек использовать реальные предметные исходники и ограничивать генеративные изменения окружением.', 'Ответная тактика: - признать обоснованность страха; - объяснить, что форма, материал, цвет, фурнитура, камни и пропорции фиксируются как критически важные признаки; - предложить контрольные сравнения с исходником; - определить допустимый и недопустимый уровень изменений до начала работы; - для точных карточек использовать реальные предметные исходники и ограничивать генеративные изменения окружением.', NULL, 'Уточнить факты и согласовать безопасный следующий шаг.', 'any', 'firm', 'recommended', 'elevated', 'notion', 'https://app.notion.com/p/3aba54abb3e281abbea5fe4f6a2df4a3?pvs=204', 'Украшения и женские аксессуары', 'approved', 1, 'priority-a-jewelry-objection-1'),
  ('ki-a-jewelry-ob2', 'objection_response', 'creator', 'objections', 'Ответ: «Покупатель получит не то, что увидел»', 'Покупатель получит не то, что увидел', 'Нужно разделить: - точный товарный контент; - рекламную атмосферную визуализацию; - концептуальные кадры. В коммерческом предложении заранее указать, где требуется абсолютная точность товара, а где допускается творческая стилизация окружения.', 'Нужно разделить: - точный товарный контент; - рекламную атмосферную визуализацию; - концептуальные кадры. В коммерческом предложении заранее указать, где требуется абсолютная точность товара, а где допускается творческая стилизация окружения.', NULL, 'Зафиксировать границы решения до начала производства.', 'any', 'firm', 'recommended', 'elevated', 'notion', 'https://app.notion.com/p/3aba54abb3e281abbea5fe4f6a2df4a3?pvs=204', 'Украшения и женские аксессуары', 'approved', 1, 'priority-a-jewelry-objection-2'),
  ('ki-a-jewelry-eth1', 'ethical_rule', 'system', 'ethics', 'Обязательная проверка: Украшения и женские аксессуары', NULL, 'Честная демонстрация товара. Скромная эстетика. Предметные кадры без людей.', 'Честная демонстрация товара. Скромная эстетика. Предметные кадры без людей.', NULL, 'Честная демонстрация товара. Скромная эстетика. Предметные кадры без людей.', 'any', 'firm', 'required', 'high', 'notion', 'https://app.notion.com/p/3aba54abb3e281abbea5fe4f6a2df4a3?pvs=204', 'Украшения и женские аксессуары', 'approved', 1, 'priority-a-jewelry-ethics-1'),
  ('ki-a-home-q1', 'question_to_client', 'creator', 'business', 'Расскажите, чем занимается бренд и какие товары являются основными', 'Расскажите, чем занимается бренд и какие товары являются основными?', NULL, NULL, NULL, NULL, 'any', 'business', 'required', 'normal', 'notion', 'https://app.notion.com/p/3aba54abb3e28169b88df88fd3771ae0?pvs=204', 'Товары для дома и эстетичного быта', 'approved', 1, 'priority-a-home-question-1'),
  ('ki-a-home-q2', 'question_to_client', 'creator', 'context', 'Вы производите товар или закупаете готовый ассортимент', 'Вы производите товар или закупаете готовый ассортимент?', NULL, NULL, NULL, NULL, 'any', 'business', 'recommended', 'normal', 'notion', 'https://app.notion.com/p/3aba54abb3e28169b88df88fd3771ae0?pvs=204', 'Товары для дома и эстетичного быта', 'approved', 1, 'priority-a-home-question-2'),
  ('ki-a-home-ob1', 'objection_response', 'creator', 'objections', 'Ответ: «Наш товар лучше показывать только вживую»', 'Наш товар лучше показывать только вживую', 'Ответ: согласиться, что точность важна. Предложить гибридную систему: реальные базовые кадры товара плюс нейросреда, которая меняет окружение, но не сам продукт.', 'Ответ: согласиться, что точность важна. Предложить гибридную систему: реальные базовые кадры товара плюс нейросреда, которая меняет окружение, но не сам продукт.', NULL, 'Уточнить факты и согласовать безопасный следующий шаг.', 'any', 'firm', 'recommended', 'elevated', 'notion', 'https://app.notion.com/p/3aba54abb3e28169b88df88fd3771ae0?pvs=204', 'Товары для дома и эстетичного быта', 'approved', 1, 'priority-a-home-objection-1'),
  ('ki-a-home-ob2', 'objection_response', 'creator', 'objections', 'Ответ: «Нейросеть исказит изделие»', 'Нейросеть исказит изделие', 'Ответ: объяснить этап проверки формы, размеров, рисунка, материала, цвета и комплектации. Для критически точных характеристик использовать исходный товар без генеративного изменения.', 'Ответ: объяснить этап проверки формы, размеров, рисунка, материала, цвета и комплектации. Для критически точных характеристик использовать исходный товар без генеративного изменения.', NULL, 'Зафиксировать границы решения до начала производства.', 'any', 'firm', 'recommended', 'elevated', 'notion', 'https://app.notion.com/p/3aba54abb3e28169b88df88fd3771ae0?pvs=204', 'Товары для дома и эстетичного быта', 'approved', 1, 'priority-a-home-objection-2'),
  ('ki-a-home-eth1', 'ethical_rule', 'system', 'ethics', 'Обязательная проверка: Товары для дома и эстетичного быта', NULL, 'Честная демонстрация товара. Отсутствие обмана в характеристиках. Скромная предметная подача.', 'Честная демонстрация товара. Отсутствие обмана в характеристиках. Скромная предметная подача.', NULL, 'Честная демонстрация товара. Отсутствие обмана в характеристиках. Скромная предметная подача.', 'any', 'firm', 'required', 'high', 'notion', 'https://app.notion.com/p/3aba54abb3e28169b88df88fd3771ae0?pvs=204', 'Товары для дома и эстетичного быта', 'approved', 1, 'priority-a-home-ethics-1'),
  ('ki-a-marketplaces-q1', 'question_to_client', 'creator', 'business', 'Что вы продаёте', 'Что вы продаёте?', NULL, NULL, NULL, NULL, 'any', 'business', 'required', 'normal', 'notion', 'https://app.notion.com/p/3aba54abb3e2819286f0eb91d4552f31?pvs=204', 'Продавцы на маркетплейсах и интернет-магазины', 'approved', 1, 'priority-a-marketplaces-question-1'),
  ('ki-a-marketplaces-q2', 'question_to_client', 'creator', 'context', 'Это собственный бренд, производство или закупной ассортимент', 'Это собственный бренд, производство или закупной ассортимент?', NULL, NULL, NULL, NULL, 'any', 'business', 'recommended', 'normal', 'notion', 'https://app.notion.com/p/3aba54abb3e2819286f0eb91d4552f31?pvs=204', 'Продавцы на маркетплейсах и интернет-магазины', 'approved', 1, 'priority-a-marketplaces-question-2'),
  ('ki-a-marketplaces-ob1', 'objection_response', 'creator', 'objections', 'Ответ: «Нам нужны просто красивые карточки»', 'Нам нужны просто красивые карточки', 'Ответ строится через уточнение: «Красоту можно создать по-разному. Чтобы она работала на продажу, важно понять, что покупатель должен заметить, понять и сделать. Давайте сначала определим главную задачу карточки.»', 'Ответ строится через уточнение: «Красоту можно создать по-разному. Чтобы она работала на продажу, важно понять, что покупатель должен заметить, понять и сделать. Давайте сначала определим главную задачу карточки.»', NULL, 'Уточнить факты и согласовать безопасный следующий шаг.', 'any', 'firm', 'recommended', 'elevated', 'notion', 'https://app.notion.com/p/3aba54abb3e2819286f0eb91d4552f31?pvs=204', 'Продавцы на маркетплейсах и интернет-магазины', 'approved', 1, 'priority-a-marketplaces-objection-1'),
  ('ki-a-marketplaces-ob2', 'objection_response', 'creator', 'objections', 'Ответ: «Нейросеть всё сделает быстро»', 'Нейросеть всё сделает быстро', 'Тактика: - объяснить, что генерация — только часть процесса; - подчеркнуть диагностику, точность товара, концепцию, отбор, ретушь, адаптацию и проверку; - показать разницу между случайной генерацией и коммерческой системой.', 'Тактика: - объяснить, что генерация — только часть процесса; - подчеркнуть диагностику, точность товара, концепцию, отбор, ретушь, адаптацию и проверку; - показать разницу между случайной генерацией и коммерческой системой.', NULL, 'Зафиксировать границы решения до начала производства.', 'any', 'firm', 'recommended', 'elevated', 'notion', 'https://app.notion.com/p/3aba54abb3e2819286f0eb91d4552f31?pvs=204', 'Продавцы на маркетплейсах и интернет-магазины', 'approved', 1, 'priority-a-marketplaces-objection-2'),
  ('ki-a-marketplaces-eth1', 'ethical_rule', 'system', 'ethics', 'Обязательная проверка: Продавцы на маркетплейсах и интернет-магазины', NULL, 'Честная демонстрация товара. Точные характеристики. Прозрачная комплектация.', 'Честная демонстрация товара. Точные характеристики. Прозрачная комплектация.', NULL, 'Честная демонстрация товара. Точные характеристики. Прозрачная комплектация.', 'any', 'firm', 'required', 'high', 'notion', 'https://app.notion.com/p/3aba54abb3e2819286f0eb91d4552f31?pvs=204', 'Продавцы на маркетплейсах и интернет-магазины', 'approved', 1, 'priority-a-marketplaces-ethics-1'),
  ('ki-a-packaged_food-q1', 'question_to_client', 'creator', 'business', 'Как давно существует бренд', 'Как давно существует бренд?', NULL, NULL, NULL, NULL, 'any', 'business', 'required', 'normal', 'notion', 'https://app.notion.com/p/3aba54abb3e281c4a8f9db2ec7ccb1e9?pvs=204', 'Упакованные продукты питания', 'approved', 1, 'priority-a-packaged_food-question-1'),
  ('ki-a-packaged_food-q2', 'question_to_client', 'creator', 'context', 'Что вы производите или продаёте', 'Что вы производите или продаёте?', NULL, NULL, NULL, NULL, 'any', 'business', 'recommended', 'normal', 'notion', 'https://app.notion.com/p/3aba54abb3e281c4a8f9db2ec7ccb1e9?pvs=204', 'Упакованные продукты питания', 'approved', 1, 'priority-a-packaged_food-question-2'),
  ('ki-a-packaged_food-ob1', 'objection_response', 'creator', 'objections', 'Ответ: «Просто сделайте аппетитно»', 'Просто сделайте аппетитно', '«Сделать аппетитно можно, но важно не создать ожидание, которому продукт не соответствует. Сначала уточним реальный вид, порцию, текстуру и главное преимущество.»', '«Сделать аппетитно можно, но важно не создать ожидание, которому продукт не соответствует. Сначала уточним реальный вид, порцию, текстуру и главное преимущество.»', NULL, 'Уточнить факты и согласовать безопасный следующий шаг.', 'any', 'firm', 'recommended', 'elevated', 'notion', 'https://app.notion.com/p/3aba54abb3e281c4a8f9db2ec7ccb1e9?pvs=204', 'Упакованные продукты питания', 'approved', 1, 'priority-a-packaged_food-objection-1'),
  ('ki-a-packaged_food-ob2', 'objection_response', 'creator', 'objections', 'Ответ: «Можно добавить больше начинки»', 'Можно добавить больше начинки', 'Нельзя изменять продукт так, чтобы покупатель получил меньше, чем ожидает. Можно выбрать удачный реальный экземпляр и правильный ракурс, но не подделывать количество начинки.', 'Нельзя изменять продукт так, чтобы покупатель получил меньше, чем ожидает. Можно выбрать удачный реальный экземпляр и правильный ракурс, но не подделывать количество начинки.', NULL, 'Зафиксировать границы решения до начала производства.', 'any', 'firm', 'recommended', 'elevated', 'notion', 'https://app.notion.com/p/3aba54abb3e281c4a8f9db2ec7ccb1e9?pvs=204', 'Упакованные продукты питания', 'approved', 1, 'priority-a-packaged_food-objection-2'),
  ('ki-a-packaged_food-eth1', 'ethical_rule', 'system', 'ethics', 'Обязательная проверка: Упакованные продукты питания', NULL, 'Продвигать халяльные продукты. Честно показывать состав и количество. Раскрывать происхождение.', 'Продвигать халяльные продукты. Честно показывать состав и количество. Раскрывать происхождение.', NULL, 'Продвигать халяльные продукты. Честно показывать состав и количество. Раскрывать происхождение.', 'any', 'firm', 'required', 'high', 'notion', 'https://app.notion.com/p/3aba54abb3e281c4a8f9db2ec7ccb1e9?pvs=204', 'Упакованные продукты питания', 'approved', 1, 'priority-a-packaged_food-ethics-1'),
  ('ki-a-islamic_goods-q1', 'question_to_client', 'creator', 'business', 'Что вы продаёте', 'Что вы продаёте?', NULL, NULL, NULL, NULL, 'any', 'business', 'required', 'normal', 'notion', 'https://app.notion.com/p/3aba54abb3e2813cbeead7677496f44a?pvs=204', 'Исламские товары', 'approved', 1, 'priority-a-islamic_goods-question-1'),
  ('ki-a-islamic_goods-q2', 'question_to_client', 'creator', 'context', 'Это собственный бренд, производство, издательство или магазин', 'Это собственный бренд, производство, издательство или магазин?', NULL, NULL, NULL, NULL, 'any', 'business', 'recommended', 'normal', 'notion', 'https://app.notion.com/p/3aba54abb3e2813cbeead7677496f44a?pvs=204', 'Исламские товары', 'approved', 1, 'priority-a-islamic_goods-question-2'),
  ('ki-a-islamic_goods-ob1', 'objection_response', 'creator', 'objections', 'Ответ: «Нам достаточно восточного фона»', 'Нам достаточно восточного фона', 'Ответ: «Восточная эстетика сама по себе не объясняет ценность товара. Сначала важно показать назначение, качество и отличие, а атмосферу использовать как поддержку, а не как замену смысла.»', 'Ответ: «Восточная эстетика сама по себе не объясняет ценность товара. Сначала важно показать назначение, качество и отличие, а атмосферу использовать как поддержку, а не как замену смысла.»', NULL, 'Уточнить факты и согласовать безопасный следующий шаг.', 'any', 'firm', 'recommended', 'elevated', 'notion', 'https://app.notion.com/p/3aba54abb3e2813cbeead7677496f44a?pvs=204', 'Исламские товары', 'approved', 1, 'priority-a-islamic_goods-objection-1'),
  ('ki-a-islamic_goods-ob2', 'objection_response', 'creator', 'objections', 'Ответ: «Добавьте любой красивый арабский текст»', 'Добавьте любой красивый арабский текст', 'Корректная позиция: Использовать можно только точный, проверенный и согласованный текст. Генерировать декоративную псевдоарабскую надпись для исламского товара недопустимо.', 'Корректная позиция: Использовать можно только точный, проверенный и согласованный текст. Генерировать декоративную псевдоарабскую надпись для исламского товара недопустимо.', NULL, 'Зафиксировать границы решения до начала производства.', 'any', 'firm', 'recommended', 'elevated', 'notion', 'https://app.notion.com/p/3aba54abb3e2813cbeead7677496f44a?pvs=204', 'Исламские товары', 'approved', 1, 'priority-a-islamic_goods-objection-2'),
  ('ki-a-islamic_goods-eth1', 'ethical_rule', 'system', 'ethics', 'Обязательная проверка: Исламские товары', NULL, 'Уважение к Корану и религиозному тексту. Точность арабского языка. Честность характеристик.', 'Уважение к Корану и религиозному тексту. Точность арабского языка. Честность характеристик.', NULL, 'Уважение к Корану и религиозному тексту. Точность арабского языка. Честность характеристик.', 'any', 'firm', 'required', 'high', 'notion', 'https://app.notion.com/p/3aba54abb3e2813cbeead7677496f44a?pvs=204', 'Исламские товары', 'approved', 1, 'priority-a-islamic_goods-ethics-1'),
  ('ki-a-books-q1', 'question_to_client', 'creator', 'business', 'Кто вы: издательство, магазин, автор или создатель пособия', 'Кто вы: издательство, магазин, автор или создатель пособия?', NULL, NULL, NULL, NULL, 'any', 'business', 'required', 'normal', 'notion', 'https://app.notion.com/p/3aba54abb3e281dcb9e5fbc0e6fd6488?pvs=204', 'Книги, издательства и образовательные товары', 'approved', 1, 'priority-a-books-question-1'),
  ('ki-a-books-q2', 'question_to_client', 'creator', 'context', 'Как давно работает проект', 'Как давно работает проект?', NULL, NULL, NULL, NULL, 'any', 'business', 'recommended', 'normal', 'notion', 'https://app.notion.com/p/3aba54abb3e281dcb9e5fbc0e6fd6488?pvs=204', 'Книги, издательства и образовательные товары', 'approved', 1, 'priority-a-books-question-2'),
  ('ki-a-books-ob1', 'objection_response', 'creator', 'objections', 'Ответ: «Книгу и так видно по обложке»', 'Книгу и так видно по обложке', 'Ответ: «Обложка показывает настроение, но покупателю часто важно понять формат, размер, развороты, структуру и кому книга подходит. Эти вопросы можно закрыть контентом, не раскрывая лишнего.»', 'Ответ: «Обложка показывает настроение, но покупателю часто важно понять формат, размер, развороты, структуру и кому книга подходит. Эти вопросы можно закрыть контентом, не раскрывая лишнего.»', NULL, 'Уточнить факты и согласовать безопасный следующий шаг.', 'any', 'firm', 'recommended', 'elevated', 'notion', 'https://app.notion.com/p/3aba54abb3e281dcb9e5fbc0e6fd6488?pvs=204', 'Книги, издательства и образовательные товары', 'approved', 1, 'priority-a-books-objection-1'),
  ('ki-a-books-ob2', 'objection_response', 'creator', 'objections', 'Ответ: «Сделайте просто атмосферно»', 'Сделайте просто атмосферно', 'Тактика: - уточнить задачу; - определить, что атмосфера должна сообщать; - соединить эмоциональные кадры с информационными.', 'Тактика: - уточнить задачу; - определить, что атмосфера должна сообщать; - соединить эмоциональные кадры с информационными.', NULL, 'Зафиксировать границы решения до начала производства.', 'any', 'firm', 'recommended', 'elevated', 'notion', 'https://app.notion.com/p/3aba54abb3e281dcb9e5fbc0e6fd6488?pvs=204', 'Книги, издательства и образовательные товары', 'approved', 1, 'priority-a-books-objection-2'),
  ('ki-a-books-eth1', 'ethical_rule', 'system', 'ethics', 'Обязательная проверка: Книги, издательства и образовательные товары', NULL, 'Показывать реальные обложки и согласованные развороты. Использовать короткие согласованные цитаты. Раскрывать структуру без чрезмерного копирования.', 'Показывать реальные обложки и согласованные развороты. Использовать короткие согласованные цитаты. Раскрывать структуру без чрезмерного копирования.', NULL, 'Показывать реальные обложки и согласованные развороты. Использовать короткие согласованные цитаты. Раскрывать структуру без чрезмерного копирования.', 'any', 'firm', 'required', 'high', 'notion', 'https://app.notion.com/p/3aba54abb3e281dcb9e5fbc0e6fd6488?pvs=204', 'Книги, издательства и образовательные товары', 'approved', 1, 'priority-a-books-ethics-1'),
  ('ki-a-bakery-q1', 'question_to_client', 'creator', 'business', 'Как устроен ваш бизнес', 'Как устроен ваш бизнес?', NULL, NULL, NULL, NULL, 'any', 'business', 'required', 'normal', 'notion', 'https://app.notion.com/p/3aba54abb3e281ad984fff44bc92a67d?pvs=204', 'Кондитерские, пекарни и десертные бренды', 'approved', 1, 'priority-a-bakery-question-1'),
  ('ki-a-bakery-q2', 'question_to_client', 'creator', 'context', 'Это домашнее производство, пекарня, кондитерская, кафе или отдельный бренд', 'Это домашнее производство, пекарня, кондитерская, кафе или отдельный бренд?', NULL, NULL, NULL, NULL, 'any', 'business', 'recommended', 'normal', 'notion', 'https://app.notion.com/p/3aba54abb3e281ad984fff44bc92a67d?pvs=204', 'Кондитерские, пекарни и десертные бренды', 'approved', 1, 'priority-a-bakery-question-2'),
  ('ki-a-bakery-ob1', 'objection_response', 'creator', 'objections', 'Ответ: «У нас и так аппетитный продукт»', 'У нас и так аппетитный продукт', 'Ответ: «Это сильная основа. Задача контента — не заменить качество продукта, а помочь покупателю быстрее увидеть вкус, размер, начинку и повод для заказа.»', 'Ответ: «Это сильная основа. Задача контента — не заменить качество продукта, а помочь покупателю быстрее увидеть вкус, размер, начинку и повод для заказа.»', NULL, 'Уточнить факты и согласовать безопасный следующий шаг.', 'any', 'firm', 'recommended', 'elevated', 'notion', 'https://app.notion.com/p/3aba54abb3e281ad984fff44bc92a67d?pvs=204', 'Кондитерские, пекарни и десертные бренды', 'approved', 1, 'priority-a-bakery-objection-1'),
  ('ki-a-bakery-ob2', 'objection_response', 'creator', 'objections', 'Ответ: «Нам нужны просто красивые фотографии»', 'Нам нужны просто красивые фотографии', 'Тактика: Уточнить, где они будут использоваться и какое действие должны вызвать. Фотография для меню, рекламного объявления и премиального запуска решает разные задачи.', 'Тактика: Уточнить, где они будут использоваться и какое действие должны вызвать. Фотография для меню, рекламного объявления и премиального запуска решает разные задачи.', NULL, 'Зафиксировать границы решения до начала производства.', 'any', 'firm', 'recommended', 'elevated', 'notion', 'https://app.notion.com/p/3aba54abb3e281ad984fff44bc92a67d?pvs=204', 'Кондитерские, пекарни и десертные бренды', 'approved', 1, 'priority-a-bakery-objection-2'),
  ('ki-a-bakery-eth1', 'ethical_rule', 'system', 'ethics', 'Обязательная проверка: Кондитерские, пекарни и десертные бренды', NULL, 'Разрешённый состав. Честная порция. Точный внешний вид.', 'Разрешённый состав. Честная порция. Точный внешний вид.', NULL, 'Разрешённый состав. Честная порция. Точный внешний вид.', 'any', 'firm', 'required', 'high', 'notion', 'https://app.notion.com/p/3aba54abb3e281ad984fff44bc92a67d?pvs=204', 'Кондитерские, пекарни и десертные бренды', 'approved', 1, 'priority-a-bakery-ethics-1'),
  ('ki-a-hospitality-q1', 'question_to_client', 'creator', 'business', 'Какой тип заведения', 'Какой тип заведения?', NULL, NULL, NULL, NULL, 'any', 'business', 'required', 'normal', 'notion', 'https://app.notion.com/p/3aba54abb3e2816ea759c85f5bd58961?pvs=204', 'Кафе, рестораны и общественное питание', 'approved', 1, 'priority-a-hospitality-question-1'),
  ('ki-a-hospitality-q2', 'question_to_client', 'creator', 'context', 'Сколько точек', 'Сколько точек?', NULL, NULL, NULL, NULL, 'any', 'business', 'recommended', 'normal', 'notion', 'https://app.notion.com/p/3aba54abb3e2816ea759c85f5bd58961?pvs=204', 'Кафе, рестораны и общественное питание', 'approved', 1, 'priority-a-hospitality-question-2'),
  ('ki-a-hospitality-ob1', 'objection_response', 'creator', 'objections', 'Ответ: «Нам нужны просто красивые ролики»', 'Нам нужны просто красивые ролики', '«Сначала важно понять, какое действие должен вызвать ролик: визит, бронь, доставка или знакомство с новым блюдом. Тогда красота будет работать на конкретную задачу.»', '«Сначала важно понять, какое действие должен вызвать ролик: визит, бронь, доставка или знакомство с новым блюдом. Тогда красота будет работать на конкретную задачу.»', NULL, 'Уточнить факты и согласовать безопасный следующий шаг.', 'any', 'firm', 'recommended', 'elevated', 'notion', 'https://app.notion.com/p/3aba54abb3e2816ea759c85f5bd58961?pvs=204', 'Кафе, рестораны и общественное питание', 'approved', 1, 'priority-a-hospitality-objection-1'),
  ('ki-a-hospitality-ob2', 'objection_response', 'creator', 'objections', 'Ответ: «Гарантируете полный зал?»', 'Гарантируете полный зал?', 'Контент влияет на внимание, восприятие и решение, но загрузка зависит также от локации, цены, кухни, отзывов, сервиса, рекламы и операционной готовности. Корректно тестировать гипотезы, но нельзя гарантировать полный зал.', 'Контент влияет на внимание, восприятие и решение, но загрузка зависит также от локации, цены, кухни, отзывов, сервиса, рекламы и операционной готовности. Корректно тестировать гипотезы, но нельзя гарантировать полный зал.', NULL, 'Зафиксировать границы решения до начала производства.', 'any', 'firm', 'recommended', 'elevated', 'notion', 'https://app.notion.com/p/3aba54abb3e2816ea759c85f5bd58961?pvs=204', 'Кафе, рестораны и общественное питание', 'approved', 1, 'priority-a-hospitality-objection-2'),
  ('ki-a-hospitality-eth1', 'ethical_rule', 'system', 'ethics', 'Обязательная проверка: Кафе, рестораны и общественное питание', NULL, 'Продвижение разрешённой еды и напитков. Честная подача. Уважение к гостю.', 'Продвижение разрешённой еды и напитков. Честная подача. Уважение к гостю.', NULL, 'Продвижение разрешённой еды и напитков. Честная подача. Уважение к гостю.', 'any', 'firm', 'required', 'high', 'notion', 'https://app.notion.com/p/3aba54abb3e2816ea759c85f5bd58961?pvs=204', 'Кафе, рестораны и общественное питание', 'approved', 1, 'priority-a-hospitality-ethics-1'),
  ('ki-a-manufacturing-q1', 'question_to_client', 'creator', 'business', 'Что вы производите', 'Что вы производите?', NULL, NULL, NULL, NULL, 'any', 'business', 'required', 'normal', 'notion', 'https://app.notion.com/p/3aba54abb3e2810ca25ed675e9158350?pvs=204', 'Производители и ремесленные мастерские', 'approved', 1, 'priority-a-manufacturing-question-1'),
  ('ki-a-manufacturing-q2', 'question_to_client', 'creator', 'context', 'Как давно работаете', 'Как давно работаете?', NULL, NULL, NULL, NULL, 'any', 'business', 'recommended', 'normal', 'notion', 'https://app.notion.com/p/3aba54abb3e2810ca25ed675e9158350?pvs=204', 'Производители и ремесленные мастерские', 'approved', 1, 'priority-a-manufacturing-question-2'),
  ('ki-a-manufacturing-ob1', 'objection_response', 'creator', 'objections', 'Ответ: «Наш товар сам себя продаёт»', 'Наш товар сам себя продаёт', 'Корректный ответ: «Сильный товар — основа. Контент помогает человеку быстрее увидеть качество, понять отличия и принять решение, особенно когда он не может потрогать изделие лично.»', 'Корректный ответ: «Сильный товар — основа. Контент помогает человеку быстрее увидеть качество, понять отличия и принять решение, особенно когда он не может потрогать изделие лично.»', NULL, 'Уточнить факты и согласовать безопасный следующий шаг.', 'any', 'firm', 'recommended', 'elevated', 'notion', 'https://app.notion.com/p/3aba54abb3e2810ca25ed675e9158350?pvs=204', 'Производители и ремесленные мастерские', 'approved', 1, 'priority-a-manufacturing-objection-1'),
  ('ki-a-manufacturing-ob2', 'objection_response', 'creator', 'objections', 'Ответ: «Нам нужны только красивые фотографии»', 'Нам нужны только красивые фотографии', 'Нужно уточнить: - для кого; - где размещаются; - что должны объяснить; - какой заказ привести. Красивый кадр для розницы и B2B-каталог решают разные задачи.', 'Нужно уточнить: - для кого; - где размещаются; - что должны объяснить; - какой заказ привести. Красивый кадр для розницы и B2B-каталог решают разные задачи.', NULL, 'Зафиксировать границы решения до начала производства.', 'any', 'firm', 'recommended', 'elevated', 'notion', 'https://app.notion.com/p/3aba54abb3e2810ca25ed675e9158350?pvs=204', 'Производители и ремесленные мастерские', 'approved', 1, 'priority-a-manufacturing-objection-2'),
  ('ki-a-manufacturing-eth1', 'ethical_rule', 'system', 'ethics', 'Обязательная проверка: Производители и ремесленные мастерские', NULL, 'Честно показывать производство. Раскрывать ручной труд. Использовать нейроконтент для окружения и подачи.', 'Честно показывать производство. Раскрывать ручной труд. Использовать нейроконтент для окружения и подачи.', NULL, 'Честно показывать производство. Раскрывать ручной труд. Использовать нейроконтент для окружения и подачи.', 'any', 'firm', 'required', 'high', 'notion', 'https://app.notion.com/p/3aba54abb3e2810ca25ed675e9158350?pvs=204', 'Производители и ремесленные мастерские', 'approved', 1, 'priority-a-manufacturing-ethics-1'),
  ('ki-a-flowers-q1', 'question_to_client', 'creator', 'business', 'Как давно работает проект', 'Как давно работает проект?', NULL, NULL, NULL, NULL, 'any', 'business', 'required', 'normal', 'notion', 'https://app.notion.com/p/3aba54abb3e2813e8611dd2d2dd62404?pvs=204', 'Цветочные магазины и подарочные сервисы', 'approved', 1, 'priority-a-flowers-question-1'),
  ('ki-a-flowers-q2', 'question_to_client', 'creator', 'context', 'Это магазин, студия, мастер или сервис', 'Это магазин, студия, мастер или сервис?', NULL, NULL, NULL, NULL, 'any', 'business', 'recommended', 'normal', 'notion', 'https://app.notion.com/p/3aba54abb3e2813e8611dd2d2dd62404?pvs=204', 'Цветочные магазины и подарочные сервисы', 'approved', 1, 'priority-a-flowers-question-2'),
  ('ki-a-flowers-ob1', 'objection_response', 'creator', 'objections', 'Ответ: «Нам нужны просто красивые картинки»', 'Нам нужны просто красивые картинки', '«Красивый визуал важен, но в цветах и подарках он должен ещё отвечать на вопросы о размере, составе, сроке и возможности повторения. Иначе изображение привлекает, а реальный заказ разочаровывает.»', '«Красивый визуал важен, но в цветах и подарках он должен ещё отвечать на вопросы о размере, составе, сроке и возможности повторения. Иначе изображение привлекает, а реальный заказ разочаровывает.»', NULL, 'Уточнить факты и согласовать безопасный следующий шаг.', 'any', 'firm', 'recommended', 'elevated', 'notion', 'https://app.notion.com/p/3aba54abb3e2813e8611dd2d2dd62404?pvs=204', 'Цветочные магазины и подарочные сервисы', 'approved', 1, 'priority-a-flowers-objection-1'),
  ('ki-a-flowers-ob2', 'objection_response', 'creator', 'objections', 'Ответ: «Можно полностью создать букеты в нейросети»', 'Можно полностью создать букеты в нейросети', 'Можно создавать атмосферные концепции и рекламные сцены, но каталог реальных заказов должен опираться на изделия, которые магазин способен собрать. Концептуальный образ нужно отделять от доступной позиции.', 'Можно создавать атмосферные концепции и рекламные сцены, но каталог реальных заказов должен опираться на изделия, которые магазин способен собрать. Концептуальный образ нужно отделять от доступной позиции.', NULL, 'Зафиксировать границы решения до начала производства.', 'any', 'firm', 'recommended', 'elevated', 'notion', 'https://app.notion.com/p/3aba54abb3e2813e8611dd2d2dd62404?pvs=204', 'Цветочные магазины и подарочные сервисы', 'approved', 1, 'priority-a-flowers-objection-2'),
  ('ki-a-flowers-eth1', 'ethical_rule', 'system', 'ethics', 'Обязательная проверка: Цветочные магазины и подарочные сервисы', NULL, 'Честно показывать цветы и подарки. Оформлять разрешённые семейные и деловые поводы. Использовать скромную предметную подачу.', 'Честно показывать цветы и подарки. Оформлять разрешённые семейные и деловые поводы. Использовать скромную предметную подачу.', NULL, 'Честно показывать цветы и подарки. Оформлять разрешённые семейные и деловые поводы. Использовать скромную предметную подачу.', 'any', 'firm', 'required', 'high', 'notion', 'https://app.notion.com/p/3aba54abb3e2813e8611dd2d2dd62404?pvs=204', 'Цветочные магазины и подарочные сервисы', 'approved', 1, 'priority-a-flowers-ethics-1')
)
INSERT OR IGNORE INTO knowledge_items (
  id, item_type, speaker, category, title, prompt_text, short_text, full_text, clarification_text, next_action_text, channel, tone, required_level, risk_level, source_kind, source_url, source_reference, status, version, normalized_key, reviewed_at, created_at, updated_at
)
SELECT
  id, item_type, speaker, category, title, prompt_text, short_text, full_text, clarification_text, next_action_text, channel, tone, required_level, risk_level, source_kind, source_url, source_reference, status, version, normalized_key, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
FROM seed;

WITH niche_map (source_slug, niche_id) AS (
  VALUES
  ('clothing', 'niche-clothing'),
  ('jewelry', 'niche-jewelry'),
  ('home', 'niche-home'),
  ('marketplaces', 'niche-marketplaces'),
  ('packaged_food', 'niche-food-packaged'),
  ('islamic_goods', 'niche-islamic'),
  ('books', 'niche-books'),
  ('bakery', 'niche-bakery'),
  ('hospitality', 'niche-horeca'),
  ('manufacturing', 'niche-manufacturing'),
  ('flowers', 'niche-flowers')
)
INSERT OR IGNORE INTO knowledge_item_niches (knowledge_item_id, niche_id, relevance)
SELECT ki.id, nm.niche_id, 'primary'
FROM knowledge_items ki
JOIN niche_map nm ON ki.id LIKE 'ki-a-' || nm.source_slug || '-%';

INSERT OR IGNORE INTO knowledge_item_stages (knowledge_item_id, stage_id)
SELECT id, 'stage-full-diagnostic'
FROM knowledge_items
WHERE id LIKE 'ki-a-%-q%';

INSERT OR IGNORE INTO knowledge_item_stages (knowledge_item_id, stage_id)
SELECT id, 'stage-objections'
FROM knowledge_items
WHERE id LIKE 'ki-a-%-ob%';

INSERT OR IGNORE INTO knowledge_item_stages (knowledge_item_id, stage_id)
SELECT id, 'stage-audit'
FROM knowledge_items
WHERE id LIKE 'ki-a-%-eth%';
